// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fizjizxvlekjbrsgdood.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpemppenh2bGVramJyc2dkb29kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MjA3MzEsImV4cCI6MjA2MjI5NjczMX0.1O0zoVjA8Sx3o3EWzzloKG6HCBYIPxW3WjxW9TkRgn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

import { initDatabaseSchema } from './schema';

// Initialize database schema when the client is initialized
const initializeSchema = async () => {
  try {
    await initDatabaseSchema(supabase);
  } catch (error) {
    console.error('Failed to initialize database schema:', error);
  }
};

// Attempt to initialize schema (this will run when the app starts)
initializeSchema();
